CREATE TABLE fiscaltickets (type VARCHAR(255) NOT NULL, sequence VARCHAR(255) NOT NULL, number INTEGER NOT NULL, date DATETIME NOT NULL, content CLOB NOT NULL, signature VARCHAR(255) NOT NULL, PRIMARY KEY(type, sequence, number));
CREATE TABLE archives (number INTEGER NOT NULL, info CLOB NOT NULL, content BLOB NOT NULL, contentHash VARCHAR(255) NOT NULL, signature VARCHAR(255) NOT NULL, PRIMARY KEY(number));
CREATE TABLE archiverequests (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, startDate DATETIME NOT NULL, stopDate DATETIME NOT NULL, processing BOOLEAN NOT NULL);
